### ISSUE TITLE
Tracking issue for phase 4 advancement

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/memory64#43]
- [x] Update spec text (https://github.com/WebAssembly/memory64/pull/50)
- [x]  #51
- [x] Rebase interpreter changes
- [x] JS API Updates
- [x] Spec tests
- [x] Implemented in at least two Web VMs 
  - [ ] v8: https://crbug.com/41480462 / https://crbug.com/364917766
- [x] Implemented in at least one toolchains
- [x] #68
  - [x] Update JS API in v8: https://g-issues.chromium.org/issues/358381633
- [x] #29
- [x] #76
- [x] #67 
- [x] #80

**Comment by rossberg** [comment]
A while ago I heard about the intent to include 64-bit tables as well, in order to be able to compile function pointers consistently. What became of that?

**Comment by sbc100** [comment]
That request came from @matthias-blume who is working on an experimental wasm to native compiler without a sandbox.

We have a workaround in llvm that truncate all function pointers before call indirect.  It add an instruction for every call indirect in the program so it could save a bit on code size and complexity if we could remove it.

Do you think it makes sense to roll it into this proposal?

**Comment by rossberg** [comment]
Yeah, from my perspective, Wasm64 is incomplete without it, and it leaves the language in an odd space. Do you think it would still be realistic to extend the proposal?

**Comment by tlively** [comment]
What's the status of the spec document? It would be good to get the changes in well ahead of the phase 4 vote at the f2f meeting.

**Comment by sbc100** [comment]
I need to pick up this open PR: https://github.com/WebAssembly/memory64/pull/50

**Comment by wooden-worm** [comment]
Now with only the table64 extension remained, can we get an estimate please?

**Comment by sbc100** [comment]
We are just waiting on the second implementation of table64 now (in spidermonkey).  My understanding is that is underway, so we should be able to vote on phase in next one or two meetings.

**Comment by bvisness** [comment]
@sbc100 Should the following two issues be added to this checklist?

- #29 (explicitly marked as release blocker)
- #67

**Comment by rossberg** [comment]
@bvisness, I'd think so.

**Comment by bvisness** [comment]
@sbc100 More issues / PRs that I think should be on this list:

- https://github.com/WebAssembly/memory64/issues/76
- https://github.com/whatwg/webidl/issues/1426

There are also the other scattered spec PRs I've been working on, but those are basically spec bugfixes and I don't think we need to track them here.

**Comment by bvisness** [comment]
https://github.com/WebAssembly/memory64/issues/80 should be on this list as well, presumably.

**Comment by sbc100** [comment]
Indeed.  Added #80, hopefully we can get those updates done by next meeting and vote on this.

**Comment by sbc100** [comment]
We are now phase 4!
